# Generated by Django 6.0.6 on 2026-06-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='192.168.1.1', max_length=50)),
                ('username', models.CharField(default='admin', max_length=100)),
                ('password', models.CharField(blank=True, default='', max_length=100)),
                ('brand', models.CharField(default='Airtel', max_length=100)),
                ('model', models.CharField(blank=True, default='Fiber Router', max_length=100)),
                ('snmp_community', models.CharField(default='public', max_length=100)),
                ('api_endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('api_token', models.CharField(blank=True, default='', max_length=255)),
                ('refresh_interval', models.IntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
