# Generated by Django 6.0.6 on 2026-06-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerconfig',
            name='serial_number',
            field=models.CharField(blank=True, default='ROUTER12345678', max_length=100),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='wan_mac',
            field=models.CharField(blank=True, default='AA:BB:CC:DD:EE:FF', max_length=100),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='wifi_password',
            field=models.CharField(blank=True, default='password123', max_length=100),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='wifi_ssid',
            field=models.CharField(blank=True, default='Airtel Zerotouch', max_length=100),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='wifi_ssid_5g',
            field=models.CharField(blank=True, default='Airtel Zerotouch_5G', max_length=100),
        ),
        migrations.AlterField(
            model_name='routerconfig',
            name='model',
            field=models.CharField(blank=True, default='H660GM-A', max_length=100),
        ),
        migrations.AlterField(
            model_name='routerconfig',
            name='password',
            field=models.CharField(blank=True, default='admin', max_length=100),
        ),
    ]
