# Generated by Django 6.0.6 on 2026-06-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_routerconfig_serial_number_routerconfig_wan_mac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default='Unknown Device', max_length=150)),
                ('ip_address', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=50, unique=True)),
                ('is_proxy_trusted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default='Managed Device', max_length=150)),
                ('ip_address', models.CharField(max_length=50)),
                ('mac_address', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('http_method', models.CharField(max_length=10)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('full_url', models.TextField()),
                ('status_code', models.IntegerField(default=200)),
                ('response_bytes', models.IntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
